### ISSUE TITLE
How to use records as classes?

### ISSUE THREAD

**Issue by pdesaulniers** [hishamhm/tl#27]
I'm playing around with tl. Right now, I'm trying to create a simple Point class. 

Here's what I came up with:

```lua
local Point = record
	x: number
	y: number
end

local PointMetatable: METATABLE = {
	__index = Point
}

local function Point_new(x: number, y: number): Point
	local self = setmetatable({}, PointMetatable) as Point

	self.x = x or 0
	self.y = y or 0

	return self
end

function Point.move(self: Point, dx: number, dy: number)
	self.x = self.x + dx 
	self.y = self.y + dy
end

local pt: Point = Point_new(1, 2)
pt:move(3, 4)
```
This appears to work. However, if I rename
```lua
local function Point_new
``` 
to
```lua
function Point.new
```
...then, the type checker throws an error when I try to call `Point.new(1, 2)`, because Point is a type:
```
cannot index something that is not a record: type {x: number, y: number, new: function(number,number):Point, move: function(Point,number,number)}
```
Is there some way for me to define the constructor as `Point.new` ? 

Also, is this a proper way of creating a class-like table in tl? Perhaps my code is not even supposed to work? :) (I understand that tl is an ongoing project, and that some features may not be fully implemented yet...)

**Comment by hishamhm** [comment]
@pdesaulniers Thank you for giving it a try and providing feedback! Yes, I believe your example _should_ work even though it doesn't right now. I'll work on the changes necessary to make it work!

**Comment by pdesaulniers** [comment]
Cool! One more thing:

If I modify Point.move so that it uses colon syntax instead:
```lua
function Point:move(dx: number, dy: number)
	self.x = self.x + dx 
	self.y = self.y + dy
end
```

Then, the following incorrect lua code is generated (there's a superfluous "self" argument):
```lua
function Point:move(self, dx, dy)
   self.x = self.x + dx
   self.y = self.y + dy
end
```

**Comment by hishamhm** [comment]
@pdesaulniers both issues should be fixed now! thank you and please keep the feedback coming! :smile:
