### ISSUE TITLE
Parameter names inside function declarations?

### ISSUE THREAD

**Issue by pdesaulniers** [hishamhm/tl#32]
The following tl code produces an error:
``` lua
local love_graphics = record
	print: function(text: string, x: number, y: number): nil
end
```

Here's the error (I'm on the definition_files branch):
```
lua: lib/tl//tl.lua:1668: attempt to index a nil value (local 'val')
stack traceback:
        lib/tl//tl.lua:1668: in function <lib/tl//tl.lua:1645>
        (...tail calls...)
        lib/tl//tl.lua:1725: in function <lib/tl//tl.lua:1712>
        (...tail calls...)
        lib/tl//tl.lua:4730: in function 'tl.process'
        lib/tl/tl:71: in main chunk
        [C]: in ?
```

I think parameter names inside function declarations should be allowed. It would make writing declaration files a bit easier. Also, text editors would be able to parse declaration files and show parameter names in tooltips.

**Comment by hishamhm** [comment]
> I think parameter names inside function declarations should be allowed. It would make writing declaration files a bit easier. Also, text editors would be able to parse declaration files and show parameter names in tooltips.

I agree! I've been annoyed myself by this at times. And also I just realized that the syntax with form `<name>: <type>` in function declarations is needed in varargs, to allow for `...: string` and the like. I'm adding this right now!
