### ISSUE TITLE
How to load declaration files that do not correspond to Lua modules

### ISSUE THREAD

**Issue by hishamhm** [hishamhm/tl#35]
Some environments like Love2D and OpenResty pre-declare globals, for which we would like to specify using declaration files. These, however, don't have a corresponding `require()` call, since they are preloaded. 

From #28:

<blockquote>
However, what if we want to declare the fields in a global created using Lua's C API? To achieve this, I think we'd have to use an empty .lua file:

application.d.tl:
```lua
global application = record
	quit: function()
end
```

application.lua:
```lua
-- Empty file; the `application` global is created in C code
```

main.tl:
```lua
require("application") -- Without the empty `application.lua` file, we'd get a 'module not found' error in the Lua code
application.quit()
```

This is a bit weird, but I don't know if there's a better way of handling this.
</blockquote>

My reply:

<blockquote>
this thought crossed my mind too. One solution would be something like:

```
tl -llove main.tl
```

This would pre-load `love.d.tl` when type checking, similar to `-l` in the lua interpreter.
</blockquote>

This would not be too hard to implement, it would be very suitable as a first contribution to the project. A bonus feature would be to load a configuration file so that one wouldn't need to pass these via the CLI every time, using a `tlconfig.lua` similar to what TypeScript does with `tsconfig.json`.

**Comment by pdesaulniers** [comment]
OK, I can take a look at this.

**Comment by hishamhm** [comment]
@pdesaulniers Awesome! If you have any doubts, feel free to hit me with questions!

**Comment by pdesaulniers** [comment]
I believe this can be closed now.

**Comment by hishamhm** [comment]
For sure! :clap:
