### ISSUE TITLE
Method definition on record imported from declaration file does not throw an error?

### ISSUE THREAD

**Issue by pdesaulniers** [hishamhm/tl#39]
I think the method definition feature is a bit inconvenient here:

love.d.tl:
```lua
global love = record
	draw: function()
end
```

main.tl:
```lua
require("love")

-- There's a typo in the function name, but the type-checker does not throw an error
function love.draws()
	print("draw stuff...")
end
```

I suppose it would be better to throw an error in this case?

**Comment by hishamhm** [comment]
This is a little tricky. It allows declaring functions over unknown keys of records to support this:

```
local my_module = {}

function my_module.my_function()
   -- ...
end
```

...which is a super common pattern.

What you might be suggesting is that `function t.unknown_key` should work differently whether the table is declared in the same file or required from a different one (or perhaps it should be a matter of scope levels instead). In any case, it's an intriguing idea.

**Comment by pdesaulniers** [comment]
Yeah, I don't know what would be the proper solution for this.

I was mostly thinking that `function t.unknown_key` should not work for records that come from declaration files. 

I might be wrong, but I don't think that records in declaration files should have functions with actual bodies:

love.d.tl
```lua
global love = record

end

function love.draw()
    -- Why should this function have a body? We're in a declaration file.
    -- The actual implementation should probably be elsewhere.
end
```

Maybe this is a terrible idea, but perhaps we could add a special keyword (such as `declare`) that disallows the `function t.unknown_key` syntax:

love.d.tl
```lua
declare global love = record
	draw: function()
end
```

main.tl
```lua
require("love")

function love.draw() -- this works, since the `draw` key is known
	print("draw stuff...")
end

function love.draws() -- error: unknown key 'draws' in 'love'
	print("draw stuff...")
end
```

(Hopefully, my explanation was clear :stuck_out_tongue: )

**Comment by hishamhm** [comment]
@pdesaulniers I made it in #48 so that it decides by scope whether it's ok or not to create a new function, the PR contains a description (and so do the tests), check it out!

**Comment by pdesaulniers** [comment]
OK, that works!

I guess this behavior might seem a bit surprising for newcomers... But then, I think it's fine for now.

Global variables should generally be avoided anyway :)

**Comment by hishamhm** [comment]
I agree, but then either `love.draws` would have to be accepted, or people would be forced to pre-declare every function in their module. At least I _think_ I managed to produce a reasonable error message that explains the situation. At one point I'd like to do what the Rust compiler does and put "pointers" in the error messages such as error code numbers, that people can easily search online and reach an explanation that's longer than one line.

**Comment by pdesaulniers** [comment]
Yep. This could be mentioned in the docs.

I think this behavior is fine for the time being.

**Comment by hishamhm** [comment]
Yeah, will definitely document it... when I get around to start the documentation! Which should probably be the next thing for me to work on!

Going to merge the PR and close this one, thanks for bouncing ideas :)
