### ISSUE TITLE
setup CI

### ISSUE THREAD

**Issue by hishamhm** [hishamhm/tl#6]
Adding this issue as a reminder. It would be good to run `make` and `tl tl.tl` in CI for pull requests (I'm most familiar with Travis, so that would be my go-to option).

**Comment by hishamhm** [comment]
@kikito Thanks!! \o/

**Comment by kikito** [comment]
@hishamhm don't forget to [activate the project inside Travis-CI](https://travis-ci.org/hishamhm/tl)!

**Comment by hishamhm** [comment]
should be active now, at least I saw a build happen!

**Comment by kikito** [comment]
Two things make me think Travis is not enabled.

This is what I see when I enter [travis for this project](https://travis-ci.org/hishamhm/tl):

<img width="1338" alt="Screenshot 2019-03-18 at 15 13 32" src="https://user-images.githubusercontent.com/63131/54536232-970f6e80-4990-11e9-8ec8-df37e416c61b.png">

Secondly, the icon in the README should be green (or red, if master was broken) but it's gray instead:

<img width="696" alt="Screenshot 2019-03-18 at 15 15 21" src="https://user-images.githubusercontent.com/63131/54536308-c7570d00-4990-11e9-9081-e2fa50f8cdf8.png">

**Comment by hishamhm** [comment]
Oh — it should be fixed now, thanks for the heads up!
