### ISSUE TITLE
Error for incomplete assignment at the end of the file

### ISSUE THREAD

**Issue by resolritter** [hishamhm/tl#68]
Installed with `luarocks --local install tl`

------

`cat bug.tl`

local Env = record
   globals: {string:Variable}
   modules: {string:Type}
end

local TypeCheckOptions = record
   lax: boolean
   env: Env
   result: Result
end

local something: TypeCheckOptions =

---

`tl check bug.tl`

/usr/bin/lua5.3: /usr/share/lua/5.3/tl.lua:4012: attempt to index a nil value (local 'last')
stack traceback:
	/usr/share/lua/5.3/tl.lua:4012: in upvalue 'get_assignment_values'
	/usr/share/lua/5.3/tl.lua:4143: in field 'after'
	/usr/share/lua/5.3/tl.lua:1822: in function </usr/share/lua/5.3/tl.lua:1816>
	(...tail calls...)
	/usr/share/lua/5.3/tl.lua:1863: in upvalue 'recurse_node'
	/usr/share/lua/5.3/tl.lua:4713: in function 'tl.type_check'
	/usr/share/lua/5.3/tl.lua:4811: in function 'tl.process'
	/usr/lib/luarocks/rocks-5.3/tl/0.1.0-1/bin/tl:115: in main chunk
	[C]: in ?

**Comment by hishamhm** [comment]
@resolritter Thank you! It's now fixed in `master`!
