### ISSUE TITLE
Commas optional in function declarations and calls?

### ISSUE THREAD

**Issue by pdesaulniers** [hishamhm/tl#75]
Apparently, this is valid TL code:
```lua
local function x(a b c)
	
end

local function y(a: string b: string c: string)
	print(a b c)
end
```
I suppose this is a bug?

**Comment by hishamhm** [comment]
@pdesaulniers Yes! Thanks for catching it! It's now fixed... and there was actually a spot in the tl source code where a comma was missing!

**Comment by hishamhm** [comment]
https://github.com/hishamhm/tl/commit/e9f85922b5cbe9c2533c992fcf9d6e6b9ef628a1#diff-25b1b7d641f7f8d0ff7b4e104bdd91d2R4561 :see_no_evil:
